rsyslog: remove pin of specific version
The current pinned version no longer works with upstream. The following
error is logged building:

ERROR: rsyslog-8.1904.0-r0 do_configure: QA Issue: rsyslog: configure was passed unrecognised options: --enable-imfile-tests [unknown-configure-option]

Some investigation has not netted any solid reason on why this is needed
anymore.

Signed-off-by: Andrew Geissler <geissonator@yahoo.com>
Change-Id: Icc795683147843d50da4ed6329edee54d939c7c3